export const specialExamNames = {
  chcm: "CHCM",
  eosinofilos: "Eosinófilos",
  hemoglobina: "Hemoglobina",
  neutrofilos: "Neutrofilos",
  hematocrito: "Hematocrito",
  leucocitos: "Leucocitos",
  plaquetas: "Plaquetas",
  linfocitos: "Linfocitos",
  monocitos: "Monocitos",
  blastos: "Blastos",
  cayado: "Cayado",
  consistencia: "Consistencia",
  moco: "Moco",
  aspecto: "Aspecto",
  reaccion: "Reacción",
  color: "Color",
  sangre: "Sangre",
  protozoarios: "Protozoarios",
  helmintos: "Helmintos",
  otros: "Otros",
  ph: "pH",
  densidad: "Densidad",
  glucosa: "Glucosa",
  proteinas: "Proteínas",
  hb: "Hb",
  bilirrubina: "Bilirrubina",
  nitritos: "Nitritos",
  urobilinogeno: "Urobilinogeno",
  pig_biliares: "Pig Biliares",
  cetona: "Cetona",
  hematies: "Hematíes",
  blastoconidios: "Blastoconidios",
  f_mucina: "F. mucina",
  bacterias: "Bacterias",
  levaduras: "Levaduras",
  piocitos: "Piocitos",
  blastoesporas: "Blastoesporas",
  trichomona_vaginalis: "Trichomona vaginalis",
  espermatozoides: "Espermatozoides",
  cristales: "Cristales",
  cristales_oxalato_calcio: "Cristales de oxalato de calcio",
  cristales_oxalato_calcio_pequenos: "Cristales de oxalato de calcio pequeños",
  cristales_oxalato_calcio_grandes: "Cristales de oxalato de calcio grandes",
  celulas: "Celulas",
  celulas_uretrales_superficiales: "Celulas uretrales superficiales",
  celulas_redondas: "Celulas redondas",
  celulas_epiteliales: "Celulas epiteliales",
};
